version: "3.3"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    restart: always
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx_proxy/nginx.conf:/etc/nginx/nginx.conf
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: ./Dockerfile  
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - "3307:3306"
  redis:
    image: redis
    restart: always
    ports:
      - "6380:6379"
